import { SanitizationPipeline } from '@sds/pipeline';
import {
  InvalidInputError,
  analyzeOptionsSchema,
  sanitizeRequestSchema,
  type AnalyzeResponse,
  type SanitizeResponse,
} from '@sds/shared';

import type { AppConfig } from '../config.js';
import { toSanitizedFileName } from '../security/filename.js';
import { type EphemeralSessionStore, type SessionRecord } from '../services/session-store.js';
import { validateUpload } from '../services/upload-validation.js';

export interface UploadPayload {
  readonly bytes: Uint8Array;
  readonly fileName: string;
  readonly mediaType: string;
  /** Raw JSON from the multipart `options` field, still unvalidated. */
  readonly rawOptions: string | undefined;
}

/**
 * Application logic for the document endpoints.
 *
 * Kept out of the route handlers on purpose: this class knows nothing about
 * Fastify, request objects or HTTP status codes. That makes the analyze /
 * sanitize flow testable directly, and it means the rule "no file processing in
 * controllers" is enforced one level further down — the controller does not
 * process files either, it delegates to `@sds/pipeline`.
 */
export class DocumentsController {
  readonly #sessions: EphemeralSessionStore;
  readonly #pipeline: SanitizationPipeline;
  readonly #config: AppConfig;

  constructor(sessions: EphemeralSessionStore, config: AppConfig) {
    this.#sessions = sessions;
    this.#config = config;
    this.#pipeline = new SanitizationPipeline({
      strictVerification: config.env.SANITIZATION_STRICT_VERIFICATION,
    });
  }

  /**
   * UPLOAD -> VALIDATE -> EXTRACT -> DETECT -> assign placeholders.
   *
   * Returns only the privacy-safe projection. The detections themselves, which
   * carry original values, stay in the session on the server.
   */
  async analyze(payload: UploadPayload): Promise<AnalyzeResponse> {
    const options = parseAnalyzeOptions(payload.rawOptions);

    const upload = validateUpload(
      {
        bytes: payload.bytes,
        declaredFileName: payload.fileName,
        declaredMediaType: payload.mediaType,
      },
      { maxFileBytes: this.#config.env.UPLOAD_MAX_FILE_BYTES },
    );

    const analysis = await this.#pipeline.analyze({
      bytes: upload.bytes,
      format: upload.format,
      options,
    });

    const session = this.#sessions.create({
      format: upload.format,
      safeFileName: upload.safeFileName,
      originalBytes: upload.bytes,
      analysis,
    });

    return {
      sessionId: session.id,
      expiresAt: new Date(session.expiresAt).toISOString(),
      document: {
        format: upload.format,
        safeFileName: upload.safeFileName,
        byteLength: upload.bytes.byteLength,
        capabilities: analysis.document.capabilities,
      },
      groups: analysis.groups,
      warnings: [...upload.notes, ...analysis.warnings],
    };
  }

  /**
   * ANONYMIZE -> GENERATE -> VERIFY.
   *
   * The generated bytes are attached to the session rather than returned, so
   * that the client receives the verification verdict first and downloads only
   * afterwards. A document that fails verification never becomes downloadable:
   * the pipeline throws before anything is attached.
   */
  async sanitize(sessionId: string, rawBody: unknown): Promise<SanitizeResponse> {
    const parsed = sanitizeRequestSchema.safeParse(rawBody ?? {});
    if (!parsed.success) {
      throw new InvalidInputError('The sanitization request was not valid.');
    }

    const session = this.#sessions.get(sessionId);

    const result = await this.#pipeline.sanitize({
      originalBytes: session.originalBytes,
      analysis: session.analysis,
      excludedPlaceholders: parsed.data.excludedPlaceholders,
    });

    this.#sessions.attachGenerated(session.id, result.generated);

    return {
      sessionId: session.id,
      verification: result.verification,
      replacedGroups: result.replacedGroups,
      replacedOccurrences: result.replacedOccurrences,
      download: {
        fileName: toSanitizedFileName(session.safeFileName),
        mediaType: result.generated.mediaType,
        byteLength: result.generated.bytes.byteLength,
      },
      warnings: [...result.warnings],
    };
  }

  /** DOWNLOAD. Returns the generated document, or fails if none was produced. */
  download(sessionId: string): { record: SessionRecord; fileName: string } {
    const record = this.#sessions.get(sessionId);

    if (record.generated === undefined) {
      throw new InvalidInputError('This document has not been sanitized yet.');
    }

    return { record, fileName: toSanitizedFileName(record.safeFileName) };
  }

  /**
   * DELETE. The user-initiated half of the retention policy; the TTL sweep is
   * the automatic half. Both are needed: a user should not have to wait fifteen
   * minutes for their document to leave our memory.
   */
  discard(sessionId: string): void {
    this.#sessions.delete(sessionId);
  }
}

function parseAnalyzeOptions(
  raw: string | undefined,
): ReturnType<typeof analyzeOptionsSchema.parse> {
  if (raw === undefined) {
    throw new InvalidInputError('Select at least one category of information to sanitize.');
  }

  let json: unknown;
  try {
    json = JSON.parse(raw);
  } catch {
    throw new InvalidInputError('The sanitization options were not valid JSON.');
  }

  const parsed = analyzeOptionsSchema.safeParse(json);
  if (!parsed.success) {
    // Zod messages describe the schema, not the payload, so they are safe to
    // return. Values are never included.
    throw new InvalidInputError(
      parsed.error.issues.map((issue) => `${issue.path.join('.')}: ${issue.message}`).join('; '),
    );
  }

  return parsed.data;
}
