import { type DocumentProcessorRegistry } from '@sds/document-processing';
import {
  type PIIType,
  type VerificationCheck,
  type VerificationReport,
  type VerificationStatus,
} from '@sds/shared';

import { normalizeHaystack, residualVariants } from './normalize.js';
import type { SanitizationVerifier, VerificationInput } from './types.js';

/**
 * The default verifier: re-extract the generated document and look for what we
 * promised to remove.
 *
 * The flow, which is the product's central safety property:
 *
 *     generated bytes -> extract text -> search for each original value
 *                     -> PASS only if none are found
 *
 * Note that it re-extracts rather than reusing the sanitized string it was
 * handed. Reusing that string would only prove our own replacement function
 * agrees with itself; re-extraction tests the thing the user actually receives,
 * including whatever the generator did to it.
 */
export class DefaultSanitizationVerifier implements SanitizationVerifier {
  readonly #registry: DocumentProcessorRegistry;

  constructor(registry: DocumentProcessorRegistry) {
    this.#registry = registry;
  }

  async verify(input: VerificationInput): Promise<VerificationReport> {
    const { generated, applied } = input;
    const checkedAt = new Date().toISOString();

    if (generated.mode === 'visual-redaction') {
      return {
        status: 'fail',
        checks: [
          {
            id: 'residual-values',
            status: 'fail',
            summary:
              'This document was only visually redacted. The underlying text is still present and extractable.',
            offendingPlaceholders: [],
          },
        ],
        unverifiedTypes: uniqueTypes(applied),
        checkedAt,
      };
    }

    let extractedText: string;
    try {
      const reExtracted = await this.#registry.extract({
        bytes: generated.bytes,
        format: generated.format,
      });
      extractedText = reExtracted.text;
    } catch {
      // Deliberately swallow the cause: it could carry document content, and it
      // does not change the outcome. Being unable to read back the output is
      // itself the finding.
      return {
        status: 'inconclusive',
        checks: [
          {
            id: 'output-parses',
            status: 'inconclusive',
            summary:
              'The generated document could not be read back, so we cannot confirm the sensitive values were removed.',
            offendingPlaceholders: [],
          },
        ],
        unverifiedTypes: uniqueTypes(applied),
        checkedAt,
      };
    }

    const checks: VerificationCheck[] = [
      residualValuesCheck(extractedText, input),
      placeholdersPresentCheck(extractedText, input),
    ];

    return {
      status: worstStatus(checks.map((check) => check.status)),
      checks,
      unverifiedTypes: [],
      checkedAt,
    };
  }
}

/**
 * The check that matters: is any original value still readable in the output?
 */
function residualValuesCheck(
  text: string,
  { applied, skipped }: VerificationInput,
): VerificationCheck {
  const haystack = normalizeHaystack(maskKeptValues(text, skipped));
  const offending = new Set<string>();

  for (const detection of applied) {
    for (const variant of residualVariants(detection.value)) {
      const found =
        haystack.lowered.includes(variant) ||
        haystack.collapsed.includes(variant) ||
        haystack.separatorless.includes(variant) ||
        (/^\d{6,}$/u.test(variant) && haystack.digits.includes(variant));

      if (found) {
        // Report the placeholder, never the residual value. A verification
        // report is returned to the client and written to logs.
        offending.add(detection.placeholder);
        break;
      }
    }
  }

  const offendingPlaceholders = [...offending].sort((a, b) => a.localeCompare(b));

  return {
    id: 'residual-values',
    status: offendingPlaceholders.length === 0 ? 'pass' : 'fail',
    summary:
      offendingPlaceholders.length === 0
        ? `No trace of the ${String(applied.length)} replaced value(s) was found in the generated document.`
        : `${String(offendingPlaceholders.length)} value(s) are still present in the generated document.`,
    offendingPlaceholders,
  };
}

/**
 * Blank out the values the user chose to keep, before searching for leaks.
 *
 * Without this, one kept value can frame another as a leak. Concretely: if the
 * user keeps `john.doe@example.com` but replaces the name "John Doe", the
 * separator-insensitive search finds "johndoe" inside the surviving email and
 * reports the name as residual. The name is not leaking — it is visible only
 * through text the user deliberately retained.
 *
 * Masking first makes the question precise: does any value we PROMISED to
 * remove still appear in the parts of the document we were responsible for?
 */
function maskKeptValues(text: string, skipped: VerificationInput['skipped']): string {
  let masked = text;
  for (const detection of skipped) {
    if (detection.value.length === 0) continue;
    masked = masked.split(detection.value).join(' ');
  }
  return masked;
}

/**
 * The complementary check: did the replacements actually land?
 *
 * A generator bug that dropped the sanitized text entirely would pass the
 * residual check trivially, by producing an empty file. Requiring the
 * placeholders to be present closes that hole.
 */
function placeholdersPresentCheck(text: string, { applied }: VerificationInput): VerificationCheck {
  const expected = new Set(applied.map((detection) => detection.placeholder));
  const missing = [...expected].filter((placeholder) => !text.includes(placeholder)).sort();

  return {
    id: 'placeholders-present',
    status: missing.length === 0 ? 'pass' : 'fail',
    summary:
      missing.length === 0
        ? `All ${String(expected.size)} placeholder(s) are present in the generated document.`
        : `${String(missing.length)} placeholder(s) are missing, so replacement did not fully apply.`,
    offendingPlaceholders: missing,
  };
}

function uniqueTypes(detections: VerificationInput['applied']): PIIType[] {
  return [...new Set(detections.map((detection) => detection.type))];
}

function worstStatus(statuses: readonly VerificationStatus[]): VerificationStatus {
  if (statuses.includes('fail')) return 'fail';
  if (statuses.includes('inconclusive')) return 'inconclusive';
  return 'pass';
}
