import { sweepPdfStructure, type DocumentProcessorRegistry } from '@cloakfile/document-processing';
import {
  type PIIType,
  type VerificationCheck,
  type VerificationReport,
  type VerificationStatus,
} from '@cloakfile/shared';

import { normalizeHaystack, residualVariantMatches, residualVariants } from './normalize.js';
import type { SanitizationVerifier, VerificationInput } from './types.js';

/**
 * The default verifier: re-extract the generated document and look for what we
 * promised to remove.
 *
 *     generated bytes -> extract text -> search for each original value
 *                     -> PASS only if none are found
 *
 * It re-extracts rather than reusing the sanitized string it was handed.
 * Reusing that string would only prove our own replacement function agrees with
 * itself; re-extraction tests the thing the user actually receives, including
 * whatever the generator did to it.
 *
 * ---------------------------------------------------------------------------
 * Why PDFs get two more checks
 * ---------------------------------------------------------------------------
 * For a text format, re-extraction is the whole story: the bytes are the text.
 * A PDF is not like that. Its text is a reconstruction through font tables, it
 * carries content in channels that text extraction never returns, and its
 * objects are compressed, so searching the file's bytes proves nothing.
 *
 * That last point is not theoretical. Re-saving a test PDF moved an annotation
 * body and the `/Info` author into a Flate-compressed object stream; searching
 * the output bytes reported both absent, while reading the file properly
 * returned both intact. A byte-level verifier would have certified a leaking
 * document as clean.
 *
 * So PDFs get:
 *
 *   `structural-channels` — assert the output has no annotations, form, XMP,
 *       attachments, JavaScript or document properties. The generator never
 *       writes these, so it cannot be the thing that hid a failure here.
 *   `deep-streams` — walk every indirect object with a *different parser*,
 *       inflate every stream, and search the decoded content. A blind spot in
 *       pdf.js's text layer is not shared by pdf-lib's object graph.
 */
export class DefaultSanitizationVerifier implements SanitizationVerifier {
  readonly #registry: DocumentProcessorRegistry;

  constructor(registry: DocumentProcessorRegistry) {
    this.#registry = registry;
  }

  async verify(input: VerificationInput): Promise<VerificationReport> {
    const { generated, applied } = input;
    const checkedAt = new Date().toISOString();

    if (generated.mode === 'visual-redaction') {
      return singleCheckReport(
        {
          id: 'residual-values',
          status: 'fail',
          summary:
            'This document was only visually redacted. The underlying text is still present and extractable.',
          offendingPlaceholders: [],
        },
        applied,
        checkedAt,
      );
    }

    let extractedText: string;
    try {
      const reExtracted = await this.#registry.extract({
        bytes: generated.bytes,
        format: generated.format,
      });
      extractedText = reExtracted.text;
    } catch {
      // Deliberately swallow the cause: it could carry document content, and it
      // does not change the outcome. Being unable to read back the output is
      // itself the finding.
      return singleCheckReport(
        {
          id: 'output-parses',
          status: 'inconclusive',
          summary:
            'The generated document could not be read back, so we cannot confirm the sensitive values were removed.',
          offendingPlaceholders: [],
        },
        applied,
        checkedAt,
      );
    }

    const checks: VerificationCheck[] = [
      residualValuesCheck(extractedText, input),
      placeholdersPresentCheck(extractedText, input),
    ];

    const unreadable = unreadableContentCheck(input);
    if (unreadable !== null) checks.push(unreadable);

    if (generated.format === 'pdf') {
      checks.push(...(await pdfStructuralChecks(input)));
    }

    return {
      status: worstStatus(checks.map((check) => check.status)),
      checks,
      unverifiedTypes: checks.some((check) => check.status !== 'pass') ? uniqueTypes(applied) : [],
      checkedAt,
    };
  }
}

/**
 * The check that matters: is any original value still readable in the output?
 */
function residualValuesCheck(text: string, input: VerificationInput): VerificationCheck {
  const offendingPlaceholders = findResidual(text, input);

  return {
    id: 'residual-values',
    status: offendingPlaceholders.length === 0 ? 'pass' : 'fail',
    summary:
      offendingPlaceholders.length === 0
        ? `No trace of the ${String(input.applied.length)} replaced value(s) was found in the generated document.`
        : `${String(offendingPlaceholders.length)} value(s) are still present in the generated document.`,
    offendingPlaceholders,
  };
}

/**
 * The same search, run over a reading of the file that does not come from the
 * text extractor — every object, every inflated stream.
 */
async function pdfStructuralChecks(input: VerificationInput): Promise<readonly VerificationCheck[]> {
  let report;
  try {
    report = await sweepPdfStructure(input.generated.bytes);
  } catch {
    return [
      {
        id: 'deep-streams',
        status: 'inconclusive',
        summary:
          'The generated PDF could not be taken apart for a second, independent check, so its contents could not be fully confirmed.',
        offendingPlaceholders: [],
      },
    ];
  }

  const offendingPlaceholders = findResidual(report.decodedText, input);
  const leftovers = describeLeftoverChannels(report.channels);

  return [
    {
      id: 'deep-streams',
      status: offendingPlaceholders.length > 0 ? 'fail' : report.truncated ? 'inconclusive' : 'pass',
      summary:
        offendingPlaceholders.length > 0
          ? `${String(offendingPlaceholders.length)} value(s) are still present inside the generated PDF's objects, even though they do not appear in its visible text.`
          : report.truncated
            ? 'The generated PDF was too large to take apart completely, so the independent check is incomplete.'
            : `Every object in the generated PDF was decompressed and searched; ${String(report.channels.objectCount)} object(s) checked, no trace found.`,
      offendingPlaceholders,
    },
    {
      id: 'structural-channels',
      status: leftovers.length === 0 ? 'pass' : 'fail',
      summary:
        leftovers.length === 0
          ? 'The generated PDF contains no annotations, form fields, embedded files, bookmarks, JavaScript, XMP or document properties.'
          : `The generated PDF still contains ${leftovers.join(', ')}, which should have been removed.`,
      offendingPlaceholders: [],
    },
  ];
}

function describeLeftoverChannels(
  channels: Awaited<ReturnType<typeof sweepPdfStructure>>['channels'],
): readonly string[] {
  const leftovers: string[] = [];
  if (channels.annotationCount > 0) {
    leftovers.push(`${String(channels.annotationCount)} annotation(s)`);
  }
  if (channels.hasAcroForm) leftovers.push('an interactive form');
  if (channels.hasEmbeddedFiles) leftovers.push('embedded files');
  if (channels.hasXmpMetadata) leftovers.push('XMP metadata');
  if (channels.hasJavaScript) leftovers.push('JavaScript actions');
  if (channels.hasOutlines) leftovers.push('bookmarks');
  if (channels.descriptiveInfoKeys.length > 0) {
    leftovers.push(`document properties (${channels.descriptiveInfoKeys.join(', ')})`);
  }
  return leftovers;
}

/**
 * Content we never managed to read in the first place.
 *
 * This cannot be a `fail` — nothing is known to be wrong — and it must not be a
 * `pass`, because the claim "we removed the sensitive values" was never tested
 * against this content. `inconclusive` is the accurate answer, and under strict
 * verification the pipeline refuses to release the file.
 */
function unreadableContentCheck({ unreadable }: VerificationInput): VerificationCheck | null {
  if (unreadable.length === 0) return null;

  return {
    id: 'unreadable-content',
    status: 'inconclusive',
    summary:
      `${String(unreadable.length)} part(s) of the original document contained no readable text — most likely scanned images. ` +
      'Anything sensitive shown only there was never visible to detection, so this document cannot be confirmed as sanitized.',
    offendingPlaceholders: [],
  };
}

function findResidual(text: string, { applied, skipped }: VerificationInput): readonly string[] {
  // Mask kept values and applied placeholders before searching. Without the
  // latter, a blocked word like "audit" replaced with `[AUDIT_001]` (or any
  // label that embeds the original token) would falsely fail residual checks.
  const haystack = normalizeHaystack(
    maskAppliedPlaceholders(maskKeptValues(text, skipped), applied),
  );
  const offending = new Set<string>();

  for (const detection of applied) {
    for (const variant of residualVariants(detection.value)) {
      if (residualVariantMatches(haystack, variant, detection.value)) {
        // Report the placeholder, never the residual value. A verification
        // report is returned to the client and written to logs.
        offending.add(detection.placeholder);
        break;
      }
    }
  }

  return [...offending].sort((a, b) => a.localeCompare(b));
}

/**
 * Blank out placeholders we intentionally wrote into the output.
 *
 * Residual search must not treat the replacement token itself as a leftover
 * original value when the label happens to contain that value (audit → AUDIT).
 */
function maskAppliedPlaceholders(
  text: string,
  applied: VerificationInput['applied'],
): string {
  let masked = text;
  for (const detection of applied) {
    if (detection.placeholder.length === 0) continue;
    masked = masked.split(detection.placeholder).join(' ');
  }
  return masked;
}

/**
 * Blank out the values the user chose to keep, before searching for leaks.
 *
 * Without this, one kept value can frame another as a leak. Concretely: if the
 * user keeps `john.doe@example.com` but replaces the name "John Doe", the
 * separator-insensitive search finds "johndoe" inside the surviving email and
 * reports the name as residual. The name is not leaking — it is visible only
 * through text the user deliberately retained.
 *
 * Masking first makes the question precise: does any value we PROMISED to
 * remove still appear in the parts of the document we were responsible for?
 */
function maskKeptValues(text: string, skipped: VerificationInput['skipped']): string {
  let masked = text;
  for (const detection of skipped) {
    if (detection.value.length === 0) continue;
    masked = masked.split(detection.value).join(' ');
  }
  return masked;
}

/**
 * The complementary check: did the replacements actually land?
 *
 * A generator bug that dropped the sanitized text entirely would pass the
 * residual check trivially, by producing an empty file. Requiring the
 * placeholders to be present closes that hole.
 */
function placeholdersPresentCheck(text: string, { applied }: VerificationInput): VerificationCheck {
  const expected = new Set(applied.map((detection) => detection.placeholder));
  const missing = [...expected].filter((placeholder) => !text.includes(placeholder)).sort();

  return {
    id: 'placeholders-present',
    status: missing.length === 0 ? 'pass' : 'fail',
    summary:
      missing.length === 0
        ? `All ${String(expected.size)} placeholder(s) are present in the generated document.`
        : `${String(missing.length)} placeholder(s) are missing, so replacement did not fully apply.`,
    offendingPlaceholders: missing,
  };
}

function singleCheckReport(
  check: VerificationCheck,
  applied: VerificationInput['applied'],
  checkedAt: string,
): VerificationReport {
  return {
    status: check.status,
    checks: [check],
    unverifiedTypes: uniqueTypes(applied),
    checkedAt,
  };
}

function uniqueTypes(detections: VerificationInput['applied']): PIIType[] {
  return [...new Set(detections.map((detection) => detection.type))];
}

function worstStatus(statuses: readonly VerificationStatus[]): VerificationStatus {
  if (statuses.includes('fail')) return 'fail';
  if (statuses.includes('inconclusive')) return 'inconclusive';
  return 'pass';
}
