import { SanitizationPipeline } from '@cloakfile/pipeline';
import type { AnalyzeOptions } from '@cloakfile/shared';
import { describe, expect, it } from 'vitest';

import {
  SAMPLE_CSV,
  SAMPLE_JSON,
  SAMPLE_TEXT,
  SAMPLE_TEXT_SECRETS,
  toBytes,
} from '../fixtures/index.js';

/**
 * The end-to-end property the whole product rests on:
 *
 *   INPUT -> DETECT -> ANONYMIZE -> GENERATE -> RE-EXTRACT -> NO ORIGINAL PII
 *
 * These tests deliberately assert on the GENERATED BYTES rather than on any
 * intermediate string. Anything less would be testing our intentions instead of
 * the artefact the user actually receives.
 *
 * As PDF and DOCX handlers land, they should be added to this same suite rather
 * than getting their own: the guarantee is format-independent, and the test
 * should read that way.
 */

const ALL_ENABLED: AnalyzeOptions = {
  enabledTypes: ['PERSON', 'EMAIL', 'PHONE', 'CREDIT_CARD', 'SSN', 'IP_ADDRESS', 'URL'],
  customPatterns: [],
};

async function sanitize(text: string, format: 'txt' | 'csv' | 'json', options = ALL_ENABLED) {
  const pipeline = new SanitizationPipeline();
  const bytes = toBytes(text);

  const analysis = await pipeline.analyze({ bytes, format, options });
  const result = await pipeline.sanitize({ originalBytes: bytes, analysis });

  return {
    analysis,
    result,
    outputText: new TextDecoder().decode(result.generated.bytes),
  };
}

describe('sanitization round trip', () => {
  it('removes every detected value from the generated document', async () => {
    const { result, outputText } = await sanitize(SAMPLE_TEXT, 'txt');

    for (const secret of SAMPLE_TEXT_SECRETS) {
      expect(outputText).not.toContain(secret);
    }

    expect(result.verification.status).toBe('pass');
  });

  it('passes its own verification step', async () => {
    const { result } = await sanitize(SAMPLE_TEXT, 'txt');

    const residual = result.verification.checks.find((check) => check.id === 'residual-values');
    expect(residual?.status).toBe('pass');
    expect(residual?.offendingPlaceholders).toEqual([]);
  });

  it('maps a repeated value onto a single placeholder', async () => {
    const { analysis, outputText } = await sanitize(SAMPLE_TEXT, 'txt');

    // The fixture mentions the same email address twice.
    const emailGroups = analysis.groups.filter((group) => group.type === 'EMAIL');
    expect(emailGroups).toHaveLength(1);
    expect(emailGroups[0]?.occurrences).toBe(2);

    const placeholder = emailGroups[0]?.placeholder ?? '';
    expect(outputText.split(placeholder).length - 1).toBe(2);
  });

  it('is deterministic: the same input yields the same placeholders', async () => {
    const first = await sanitize(SAMPLE_TEXT, 'txt');
    const second = await sanitize(SAMPLE_TEXT, 'txt');

    expect(second.outputText).toBe(first.outputText);
  });

  it('leaves a value in place when the user excludes its placeholder', async () => {
    const pipeline = new SanitizationPipeline();
    const bytes = toBytes(SAMPLE_TEXT);
    const analysis = await pipeline.analyze({ bytes, format: 'txt', options: ALL_ENABLED });

    const emailGroup = analysis.groups.find((group) => group.type === 'EMAIL');
    expect(emailGroup).toBeDefined();

    // Verification must still pass: an excluded value was never promised.
    const result = await pipeline.sanitize({
      originalBytes: bytes,
      analysis,
      excludedPlaceholders: [emailGroup?.placeholder ?? ''],
    });

    const outputText = new TextDecoder().decode(result.generated.bytes);
    expect(outputText).toContain('john.doe@example.com');
    expect(result.verification.status).toBe('pass');
  });

  it('never exposes an original value in the client-facing groups', async () => {
    const { analysis } = await sanitize(SAMPLE_TEXT, 'txt');
    const serialised = JSON.stringify(analysis.groups);

    for (const secret of SAMPLE_TEXT_SECRETS) {
      expect(serialised).not.toContain(secret);
    }
    // Not even the card's leading digits, only the last four.
    expect(serialised).not.toContain('4111 1111');
  });

  it('keeps a CSV parseable and structurally unchanged', async () => {
    const { outputText } = await sanitize(SAMPLE_CSV, 'csv');

    const originalRows = SAMPLE_CSV.split('\n');
    const outputRows = outputText.split('\n');

    expect(outputRows).toHaveLength(originalRows.length);
    expect(outputRows[0]).toBe('name,email,phone');
    expect(outputText).not.toContain('john.doe@example.com');
  });

  it('keeps JSON valid after replacement', async () => {
    const { outputText } = await sanitize(SAMPLE_JSON, 'json');

    expect(() => JSON.parse(outputText) as unknown).not.toThrow();
    expect(outputText).not.toContain('john.doe@example.com');
  });

  it('reports a category with no detector instead of implying coverage', async () => {
    const { analysis } = await sanitize(SAMPLE_TEXT, 'txt', {
      enabledTypes: ['ADDRESS'],
      customPatterns: [],
    });

    expect(analysis.warnings.join(' ')).toContain('no detector is implemented');
  });
});
