import { SanitizationPipeline } from '@cloakfile/pipeline';
import type { AnalyzeOptions } from '@cloakfile/shared';
import { describe, expect, it } from 'vitest';

import { createDefaultDocumentRegistry } from '@cloakfile/document-processing';

import {
  SAMPLE_CSV,
  SAMPLE_JSON,
  SAMPLE_TEXT,
  SAMPLE_TEXT_SECRETS,
  toBytes,
} from '../fixtures/index.js';
import { docxPackage } from '../fixtures/docx.js';
import {
  HOSTILE_PDF_SECRETS,
  hostilePdf,
  multiPagePdf,
  simpleTextPdf,
} from '../fixtures/pdf.js';

/**
 * The end-to-end property the whole product rests on:
 *
 *   INPUT -> DETECT -> ANONYMIZE -> GENERATE -> RE-EXTRACT -> NO ORIGINAL PII
 *
 * These tests deliberately assert on the GENERATED BYTES rather than on any
 * intermediate string. Anything less would be testing our intentions instead of
 * the artefact the user actually receives.
 *
 * As PDF and DOCX handlers land, they should be added to this same suite rather
 * than getting their own: the guarantee is format-independent, and the test
 * should read that way.
 */

const ALL_ENABLED: AnalyzeOptions = {
  enabledTypes: ['PERSON', 'EMAIL', 'PHONE', 'CREDIT_CARD', 'SSN', 'IP_ADDRESS', 'URL'],
  customPatterns: [],
};

async function sanitize(text: string, format: 'txt' | 'csv' | 'json', options = ALL_ENABLED) {
  const pipeline = new SanitizationPipeline();
  const bytes = toBytes(text);

  const analysis = await pipeline.analyze({ bytes, format, options });
  const result = await pipeline.sanitize({ originalBytes: bytes, analysis });

  return {
    analysis,
    result,
    outputText: new TextDecoder().decode(result.generated.bytes),
  };
}

const PDF_ENABLED: AnalyzeOptions = {
  ...ALL_ENABLED,
  // Without a region, a national-format number is ambiguous and correctly goes
  // undetected. The fixtures use Canadian numbers.
  defaultRegion: 'CA',
};

/**
 * Note that `outputText` here comes from re-extracting the generated PDF, not
 * from decoding its bytes. Decoding would be meaningless: PDF objects are
 * compressed, so a value can be absent from the bytes and fully present in the
 * document.
 */
async function sanitizePdf(bytes: Uint8Array, options = PDF_ENABLED) {
  const pipeline = new SanitizationPipeline();

  const analysis = await pipeline.analyze({ bytes, format: 'pdf', options });
  const result = await pipeline.sanitize({ originalBytes: bytes, analysis });

  const reExtracted = await createDefaultDocumentRegistry().extract({
    bytes: result.generated.bytes,
    format: 'pdf',
  });

  return { analysis, result, outputText: reExtracted.text };
}

describe('sanitization round trip', () => {
  it('removes every detected value from the generated document', async () => {
    const { result, outputText } = await sanitize(SAMPLE_TEXT, 'txt');

    for (const secret of SAMPLE_TEXT_SECRETS) {
      expect(outputText).not.toContain(secret);
    }

    expect(result.verification.status).toBe('pass');
  });

  it('passes its own verification step', async () => {
    const { result } = await sanitize(SAMPLE_TEXT, 'txt');

    const residual = result.verification.checks.find((check) => check.id === 'residual-values');
    expect(residual?.status).toBe('pass');
    expect(residual?.offendingPlaceholders).toEqual([]);
  });

  it('maps a repeated value onto a single placeholder', async () => {
    const { analysis, outputText } = await sanitize(SAMPLE_TEXT, 'txt');

    // The fixture mentions the same email address twice.
    const emailGroups = analysis.groups.filter((group) => group.type === 'EMAIL');
    expect(emailGroups).toHaveLength(1);
    expect(emailGroups[0]?.occurrences).toBe(2);

    const placeholder = emailGroups[0]?.placeholder ?? '';
    expect(outputText.split(placeholder).length - 1).toBe(2);
  });

  it('is deterministic: the same input yields the same placeholders', async () => {
    const first = await sanitize(SAMPLE_TEXT, 'txt');
    const second = await sanitize(SAMPLE_TEXT, 'txt');

    expect(second.outputText).toBe(first.outputText);
  });

  it('leaves a value in place when the user excludes its placeholder', async () => {
    const pipeline = new SanitizationPipeline();
    const bytes = toBytes(SAMPLE_TEXT);
    const analysis = await pipeline.analyze({ bytes, format: 'txt', options: ALL_ENABLED });

    const emailGroup = analysis.groups.find((group) => group.type === 'EMAIL');
    expect(emailGroup).toBeDefined();

    // Verification must still pass: an excluded value was never promised.
    const result = await pipeline.sanitize({
      originalBytes: bytes,
      analysis,
      excludedPlaceholders: [emailGroup?.placeholder ?? ''],
    });

    const outputText = new TextDecoder().decode(result.generated.bytes);
    expect(outputText).toContain('john.doe@example.com');
    expect(result.verification.status).toBe('pass');
  });

  it('shows found values in the client-facing groups for review', async () => {
    const { analysis } = await sanitize(SAMPLE_TEXT, 'txt');

    expect(analysis.groups.some((group) => group.preview.includes('@'))).toBe(true);
    expect(analysis.groups.every((group) => group.preview.length > 0)).toBe(true);
  });

  it('keeps a CSV parseable and structurally unchanged', async () => {
    const { outputText } = await sanitize(SAMPLE_CSV, 'csv');

    const originalRows = SAMPLE_CSV.split('\n');
    const outputRows = outputText.split('\n');

    expect(outputRows).toHaveLength(originalRows.length);
    expect(outputRows[0]).toBe('name,email,phone');
    expect(outputText).not.toContain('john.doe@example.com');
  });

  it('keeps JSON valid after replacement', async () => {
    const { outputText } = await sanitize(SAMPLE_JSON, 'json');

    expect(() => JSON.parse(outputText) as unknown).not.toThrow();
    expect(outputText).not.toContain('john.doe@example.com');
  });

  it('reports a category with no detector instead of implying coverage', async () => {
    const { analysis } = await sanitize(SAMPLE_TEXT, 'txt', {
      enabledTypes: ['DATE_OF_BIRTH'],
      customPatterns: [],
    });

    expect(analysis.warnings.join(' ')).toContain('no detector is implemented');
  });
});

/**
 * The same guarantee, for PDF.
 *
 * These belong here rather than in a PDF-only file because the property is
 * format-independent: whatever the format, the original must not survive into
 * the bytes we hand back. Only the way of reading those bytes differs — for a
 * PDF, "read the output" means parsing it, never searching it, since its
 * objects are compressed.
 */
describe('sanitization round trip · pdf', () => {
  it('removes every detected value from the generated PDF', async () => {
    const { result, outputText } = await sanitizePdf(await simpleTextPdf());

    expect(outputText).not.toContain('John Doe');
    expect(outputText).not.toContain('514-555-0132');
    expect(outputText).not.toContain('4111');
    expect(outputText).not.toContain('john.doe@example.com');
    expect(result.verification.status).toBe('pass');
  });

  it('replaces text rather than covering it', async () => {
    const { outputText } = await sanitizePdf(await simpleTextPdf());

    // The user's own example, end to end.
    expect(outputText).toContain("[PERSON_001]'s phone number is [PHONE_001].");
  });

  it('is deterministic: the same PDF yields byte-identical output', async () => {
    const input = await simpleTextPdf();
    const first = await sanitizePdf(input);
    const second = await sanitizePdf(input);

    expect(Buffer.from(second.result.generated.bytes)).toEqual(
      Buffer.from(first.result.generated.bytes),
    );
  });

  it('maps a repeated value onto a single placeholder across pages', async () => {
    const { analysis, outputText } = await sanitizePdf(await multiPagePdf(3));

    const emailGroups = analysis.groups.filter((group) => group.type === 'EMAIL');
    expect(emailGroups).toHaveLength(1);
    expect(emailGroups[0]?.occurrences).toBe(3);
    expect(outputText.split('[EMAIL_001]').length - 1).toBe(3);
  });

  it('redacts a user-blocked word in a PDF the same way as in text', async () => {
    const bytes = await simpleTextPdf();
    const pipeline = new SanitizationPipeline();
    const analysis = await pipeline.analyze({
      bytes,
      format: 'pdf',
      options: {
        enabledTypes: ['CUSTOM'],
        customPatterns: [{ name: 'BLOCKED_NAME', pattern: '\\bJohn\\s+Doe\\b', ignoreCase: true }],
        defaultRegion: 'CA',
      },
    });

    expect(analysis.groups.some((group) => group.type === 'CUSTOM')).toBe(true);

    const result = await pipeline.sanitize({ originalBytes: bytes, analysis });
    const output = await createDefaultDocumentRegistry().extract({
      bytes: result.generated.bytes,
      format: 'pdf',
    });

    expect(result.verification.status).toBe('pass');
    expect(output.text).not.toMatch(/John\s+Doe/iu);
    expect(output.text).toContain('[BLOCKED_NAME_001]');
  });

  it('shows found values in the client-facing groups for review', async () => {
    const { analysis } = await sanitizePdf(hostilePdf());

    expect(analysis.groups.length).toBeGreaterThan(0);
    expect(analysis.groups.every((group) => group.preview.length > 0)).toBe(true);
  });

  it('declares content-removal, not visual redaction', async () => {
    const { result } = await sanitizePdf(await simpleTextPdf());

    expect(result.generated.mode).toBe('content-removal');
  });
});

describe('sanitization round trip · docx', () => {
  it('replaces text in the body, header, metadata and table without gluing cells', async () => {
    const bytes = docxPackage([
      {
        name: 'word/document.xml',
        content: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p><w:r><w:t>Jo</w:t></w:r><w:r><w:t>hn Doe's phone number is +1 514-555-0132.</w:t></w:r></w:p>
    <w:tbl><w:tr>
      <w:tc><w:p><w:r><w:t>Tariq Ibn Ziyad</w:t></w:r></w:p></w:tc>
      <w:tc><w:p><w:r><w:t>Systems Architecture</w:t></w:r></w:p></w:tc>
    </w:tr></w:tbl>
  </w:body>
</w:document>`,
      },
      {
        name: 'word/header1.xml',
        content: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:hdr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:p><w:r><w:t>Prepared by John Doe</w:t></w:r></w:p>
</w:hdr>`,
      },
      {
        name: 'docProps/core.xml',
        content: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <dc:creator>John Doe</dc:creator>
</cp:coreProperties>`,
      },
    ]);

    const pipeline = new SanitizationPipeline();
    const analysis = await pipeline.analyze({ bytes, format: 'docx', options: PDF_ENABLED });
    const result = await pipeline.sanitize({ originalBytes: bytes, analysis });
    const output = await createDefaultDocumentRegistry().extract({
      bytes: result.generated.bytes,
      format: 'docx',
    });

    expect(result.verification.status).toBe('pass');
    expect(result.generated.mode).toBe('text-replacement');
    expect(output.text).not.toContain('John Doe');
    expect(output.text).not.toContain('Tariq Ibn Ziyad');
    expect(output.text).not.toContain('514-555-0132');
    expect(output.text).toContain("[PERSON_001]'s phone number is [PHONE_001].");
    expect(output.text).toContain('Systems Architecture');
    expect(output.text.split('[PERSON_001]').length - 1).toBeGreaterThanOrEqual(3);
  });
});
